development:
  adapter: postgresql
  database: hylo-upload-dev
  host: localhost
  username: postgres
  password: postgres
  encoding: utf8
  port: 5432

test:
  adapter: postgresql
  database: hylo-upload-tst
  host: localhost
  username: postgres
  password: postgres
  encoding: utf8
  port: 5432


production:
  adapter: postgresql
  database: hylo-upload-prod
  host: localhost
  username: postgres
  password: postgres
  encoding: utf8
  port: 5432

